#!/usr/bin/env python3
"""
RADIATIVE b/a SPLITTING: RGE FROM M_C TO v_R
==============================================

The tree-level b/a = 0 (Killing form invariance) holds at M_C.
Below M_C, SU(4) is broken to SU(3) × U(1)_{B-L}.
The (15,2,2) Yukawa coupling is radiatively generated by:
  1. Gauge loops: different SU(3)_c and U(1)_{B-L} gauge couplings
     act differently on quarks vs leptons
  2. Yukawa loops: the existing (1,2,2) Yukawa feeds back differently
     for different SU(4) components

This splitting modifies the Dirac mass relation:
  m_D(ν_i) = m_D(u_i) × [1 + δ_i(μ)]

where δ_i is the radiative correction, which is GENERATION-DEPENDENT
because it involves the Yukawa couplings.

The key question: is δ₃ large enough to reduce m_ν₃ from 10 keV to 0.05 eV?
This requires δ₃ such that m_D(ν₃) / m_D(t) ~ 1/400, i.e., δ₃ ~ -0.998.
That's a 99.8% correction — radiative effects can't do this.

OR: the splitting needs to go as a RATIO m_D(ν)/m_u at low energy,
and the RG running of this ratio from M_C to v_R tells us the answer.

In Pati-Salam, the Yukawa matrix at M_C is:
  Y = a(M_C) × I₄ + b(M_C) × T₁₅
where T₁₅ = diag(-3, 1, 1, 1)/√(12) is the B-L generator.

This gives:
  Y_u = a + b/(2√3)    (quarks: T₁₅ = +1/(2√3))
  Y_ν = a - 3b/(2√3)   (leptons: T₁₅ = -3/(2√3))

So: m_D(ν)/m_D(u) = (a - √3 b) / (a + b/√3)
With b/a = 0: ratio = 1 (exact SU(4))

Below M_C, the ratio runs due to different gauge corrections for quarks and leptons.

Author: Metric Bundle Programme, March 2026
"""

import numpy as np
from scipy.integrate import solve_ivp
np.set_printoptions(precision=8, suppress=True, linewidth=120)

print("=" * 72)
print("RADIATIVE b/a SPLITTING: RGE FROM M_C TO v_R")
print("=" * 72)

# =====================================================================
# PART 1: THE PHYSICS OF QUARK-LEPTON MASS SPLITTING
# =====================================================================

print("""
PART 1: QUARK-LEPTON YUKAWA SPLITTING IN PATI-SALAM

In Pati-Salam, quarks and leptons are unified in SU(4) multiplets:
  ψ_L = (4, 2, 1): contains (u, d, u, d)_color + (ν, e)
  ψ_R = (4, 1, 2): contains (u, d, u, d)_color + (ν, e)

At the PS scale M_C, the Yukawa is:
  Y = diag(y_u, y_u, y_u, y_ν)   (in SU(4) space, for each generation)
  = a × I₄ + b × T₁₅

where T₁₅ = diag(1, 1, 1, -3)/(2√3) is the B-L generator of SU(4).

The SU(4) relation at M_C:
  y_ν = y_u   when b/a = 0  (tree-level geometry)

Below M_C, SU(4) → SU(3)_c × U(1)_{B-L}. The quark and lepton Yukawas
run DIFFERENTLY because:
  - Quarks feel SU(3)_c (strong force): y_q gets enhanced
  - Leptons don't feel SU(3)_c: y_ℓ runs more slowly
  - U(1)_{B-L} charges differ: q = +1/3 for quarks, q = -1 for leptons

The one-loop RGE for Yukawa couplings in the LR model:
  16π² dy_u/dt = y_u [T_u - (8g₃² + 3g₂L² + 3g₂R²)/4 - (1/9)g_BL²]
  16π² dy_ν/dt = y_ν [T_ν - (3g₂L² + 3g₂R²)/4 - g_BL²]

where t = ln(μ) and T is the Yukawa trace contribution.
""")

# =====================================================================
# PART 2: ONE-LOOP RGE FOR YUKAWA RATIO
# =====================================================================

print("=" * 72)
print("PART 2: ONE-LOOP RGE FOR y_ν / y_u RATIO")
print("=" * 72)

# The ratio R = y_ν / y_u satisfies:
# 16π² dR/dt = R × [T_ν - T_u + 8g₃²/4 + (1/9)g_BL² - g_BL²]
#            = R × [T_ν - T_u + 2g₃² - (8/9)g_BL²]
#
# In the LR symmetric model (SU(3) × SU(2)_L × SU(2)_R × U(1)_{B-L}):
# The Yukawa trace terms T_u and T_ν depend on which generation we consider.
#
# For the RATIO, the SU(2) contributions cancel (same for quarks and leptons).
# What remains is:
#   d ln R / dt = (1/16π²) [-2g₃² + (8/9)g_BL²]  (from gauge loops)
#                + (Yukawa trace differences)
#
# Wait — the sign matters. Let me be more careful.
#
# Standard RGE for up-quark Yukawa in SU(3)×SU(2)_L×SU(2)_R×U(1)_{BL}:
# (following Mohapatra & Parida, or Babu & Mohapatra)
#
# 16π² dy_u/dt = y_u × [Tr(3 y_u†y_u + 3 y_d†y_d + y_ν†y_ν + y_e†y_e)
#                         + (3/2)(y_u†y_u + y_d†y_d)
#                         - 8g₃² - (9/4)g₂L² - (9/4)g₂R² - (1/36)g_BL²]
#
# Wait, the BL charge assignments: quarks have B-L = 1/3, leptons have B-L = -1
# In the LR model, the U(1)_{B-L} gauge coupling contributes:
#   Δ(gauge) = -C₂(BL) × g_BL²
# where C₂ depends on the representation.
#
# For a fermion with B-L charge Q_{BL}:
#   Δ = -Q_{BL}² × g_BL²
#
# So: quarks (Q=1/3): Δ_q = -(1/9) g_BL²
#     leptons (Q=-1):  Δ_ℓ = -g_BL²
#
# The DIFFERENCE in the RGE for y_ν vs y_u from GAUGE loops:
# Δ_gauge = Δ_ℓ - Δ_q = -g_BL² + (1/9)g_BL² + 8g₃²
#         = -(8/9)g_BL² + 8g₃²   [no SU(3) for leptons → add +8g₃² to lepton side]
#
# Wait, I need to think about this more carefully.
# The gauge contribution to y_u: -8g₃² - ... - (1/9)g_BL²  (quarks feel SU(3))
# The gauge contribution to y_ν:         - ... - g_BL²       (leptons don't feel SU(3))
#
# So d ln(y_ν/y_u)/dt = (1/16π²) [gauge_ν - gauge_u]
#                      = (1/16π²) [(-g_BL²) - (-8g₃² - (1/9)g_BL²)]
#                      = (1/16π²) [8g₃² - (8/9)g_BL²]

# This is POSITIVE (since g₃ >> g_BL at most scales).
# y_ν/y_u INCREASES as we run DOWN from M_C.
# This means m_D(ν) > m_D(u) at low energy — the splitting goes the WRONG WAY!

print("""
KEY INSIGHT: The gauge correction to the Yukawa ratio is:

  d ln(y_ν/y_u)/dt = (1/16π²) × [8g₃² - (8/9)g_BL²]

Since g₃ >> g_BL at all scales below M_C:
  → y_ν/y_u INCREASES as we run DOWN from M_C
  → m_D(ν) GROWS relative to m_D(u) at low energy
  → The splitting goes the WRONG WAY!

This is well known in GUT physics: the SU(3) gauge correction
ENHANCES quark masses relative to lepton masses (or equivalently,
SUPPRESSES quark Yukawas relative to lepton Yukawas, making the
RATIO y_ν/y_u grow).

In SU(5) GUTs, this is why m_b ≠ m_τ at low energy despite
m_b = m_τ at M_GUT. The famous Georgi-Jarlskog relation uses this.
""")

# =====================================================================
# PART 3: NUMERICAL COMPUTATION
# =====================================================================

print("=" * 72)
print("PART 3: NUMERICAL RGE RUNNING")
print("=" * 72)

# Physical parameters
M_C = 4.5e16  # GeV (PS breaking)
v_R = 1.1e9   # GeV (LR breaking)
M_Z = 91.2    # GeV

# Gauge couplings at M_Z (PDG 2024)
alpha_s_MZ = 0.1179
alpha_em_MZ = 1/127.9
sin2_thetaW = 0.2312

# SM gauge couplings at M_Z
alpha_1_MZ = alpha_em_MZ / (1 - sin2_thetaW)  # U(1)_Y
alpha_2_MZ = alpha_em_MZ / sin2_thetaW         # SU(2)_L
alpha_3_MZ = alpha_s_MZ                         # SU(3)_c

print(f"Gauge couplings at M_Z:")
print(f"  α₁ = {alpha_1_MZ:.4f}  (α₁⁻¹ = {1/alpha_1_MZ:.2f})")
print(f"  α₂ = {alpha_2_MZ:.4f}  (α₂⁻¹ = {1/alpha_2_MZ:.2f})")
print(f"  α₃ = {alpha_3_MZ:.4f}  (α₃⁻¹ = {1/alpha_3_MZ:.2f})")

# Running from M_Z to v_R (SM beta functions)
# b_i^SM = (41/10, -19/6, -7)
b_SM = np.array([41/10, -19/6, -7])

t_MZ = np.log(M_Z)
t_vR = np.log(v_R)
t_MC = np.log(M_C)

alpha_inv_MZ = np.array([1/alpha_1_MZ, 1/alpha_2_MZ, 1/alpha_3_MZ])

# SM running: M_Z → v_R
dt_SM = (t_vR - t_MZ) / (2 * np.pi)
alpha_inv_vR_SM = alpha_inv_MZ - b_SM * dt_SM

print(f"\nGauge couplings at v_R = {v_R:.2e} GeV (SM running):")
for i, name in enumerate(["α₁(Y)", "α₂(L)", "α₃(c)"]):
    print(f"  {name}⁻¹ = {alpha_inv_vR_SM[i]:.2f}")

# At v_R, match to LR model:
# SM: U(1)_Y × SU(2)_L × SU(3)_c
# LR: U(1)_{BL} × SU(2)_L × SU(2)_R × SU(3)_c
#
# Matching:
# 1/α_Y = 3/5 × 1/α_R + 2/5 × 1/α_BL  (standard GUT normalization)
# Actually in PS normalization:
# Y = T³_R + (B-L)/2
# α_Y⁻¹ = α_R⁻¹ + α_BL⁻¹  (roughly)
# More precisely:
# 1/α_Y = 2/(3 α_BL) + 1/α_R   (with standard PS normalization for BL)

# Let's use the LR beta functions from zero_parameter_rg.py
# Between v_R and M_C, the gauge group is SU(3) × SU(2)_L × SU(2)_R × U(1)_{BL}
# Beta coefficients (with Φ + Δ_R + Δ_L = scenario B):

# From zero_parameter_rg.py, the LR beta coefficients:
# b₃ = -7 + 4/3 × N_g + scalar contributions
# b₂L = -22/3 + 4/3 × N_g + 1/6 × n_Φ + 2/3 × n_Δ_L
# b₂R = -22/3 + 4/3 × N_g + 1/6 × n_Φ + 2/3 × n_Δ_R
# b_BL = (complicated)

# For scenario B (Φ + Δ_R + Δ_L), from scalar_spectrum_mr.py:
b_LR = np.array([-7.0, -10/3, -10/3, 7.0])  # b₃, b₂L, b₂R, b_BL
# Hmm, these don't match. Let me use the values from the scalar scan.
# From scalar_spectrum_mr.py output, scenario B:
b_LR = np.array([-7.0, -7/3, -7/3, 7.0])
# Actually let me recompute carefully.

# LR model beta coefficients (1-loop, minimal = Φ(1,2,2) + Δ_R(1,1,3) + Δ_L(1,3,1)):
N_g = 3  # generations

# SU(3)_c:
b3 = -11 + (4/3)*N_g  # = -11 + 4 = -7
# SU(2)_L:
b2L = -22/3 + (4/3)*N_g + (1/6)*1 + (2/3)*1  # Φ + Δ_L
# = -22/3 + 4 + 1/6 + 2/3 = -22/3 + 4 + 5/6 = -22/3 + 29/6 = -44/6 + 29/6 = -15/6 = -5/2
# Hmm, need to be more careful with the scalar contributions
# Actually:
# SU(2)_L with 1 bidoublet Φ and 1 triplet Δ_L:
# fermion: (4/3) × 3 = 4
# Φ = (2,2) under SU(2)_L × SU(2)_R: contributes T(2) × d_R = (1/2) × 2 = 1 per complex
# Δ_L = (3,1): contributes T(3) = 2 per complex
# But these are COMPLEX scalars, so each contributes 1/3 of the fermion:
# scalar: (1/6) × [2 (from Φ, 2 SU(2)_R components)] + (1/3) × [Δ_L]
# This gets complicated. Let me just use the standard result.

# Standard 1-loop LR beta coefficients (Mohapatra-Parida):
# With N_g generations, n_Φ bidoublets, n_ΔL left triplets, n_ΔR right triplets:
# b_3 = -11 + (4/3)N_g
# b_2L = -22/3 + (4/3)N_g + (1/6)n_Φ + (4/3)n_ΔL
# b_2R = -22/3 + (4/3)N_g + (1/6)n_Φ + (4/3)n_ΔR
# b_BL = (4/3)N_g × [4/3 × 3 + 4] + n_Φ × 0 + n_ΔL × 8 + n_ΔR × 8
# The BL one is more complicated. Let me use the values from the scalar scan directly.

# From scalar_spectrum_mr.py output, scenario B (Φ + Δ_R + Δ_L):
b3_LR = -7.0
b2L_LR = -7/3  # = -2.333
b2R_LR = -7/3
bBL_LR = 7.0

print(f"\nLR beta coefficients (scenario B: Φ + Δ_R + Δ_L):")
print(f"  b₃ = {b3_LR:.3f}")
print(f"  b₂L = {b2L_LR:.3f}")
print(f"  b₂R = {b2R_LR:.3f}")
print(f"  b_BL = {bBL_LR:.3f}")

# At M_C, all couplings unify: α₃ = α₂L = α₂R = α_BL/C_BL = α_PS
# α_PS⁻¹ ~ 46 (from zero_parameter_rg.py)
alpha_PS_inv = 46.2
alpha_PS = 1/alpha_PS_inv

print(f"\nAt M_C: α_PS⁻¹ = {alpha_PS_inv:.1f}, α_PS = {alpha_PS:.5f}")

# Run gauge couplings from M_C down to v_R
dt_LR = (t_MC - t_vR) / (2 * np.pi)  # = ln(M_C/v_R) / (2π)
print(f"  ln(M_C/v_R) = {np.log(M_C/v_R):.2f}")
print(f"  dt = ln(M_C/v_R)/(2π) = {dt_LR:.2f}")

alpha3_inv_vR = alpha_PS_inv + b3_LR * dt_LR
alpha2L_inv_vR = alpha_PS_inv + b2L_LR * dt_LR
alpha2R_inv_vR = alpha_PS_inv + b2R_LR * dt_LR
alphaBL_inv_vR = alpha_PS_inv + bBL_LR * dt_LR

print(f"\nGauge couplings at v_R = {v_R:.2e} GeV (LR running from M_C):")
print(f"  α₃⁻¹ = {alpha3_inv_vR:.2f}  (α₃ = {1/alpha3_inv_vR:.5f})")
print(f"  α₂L⁻¹ = {alpha2L_inv_vR:.2f}")
print(f"  α₂R⁻¹ = {alpha2R_inv_vR:.2f}")
print(f"  α_BL⁻¹ = {alphaBL_inv_vR:.2f}  (α_BL = {1/alphaBL_inv_vR:.5f})")

g3_sq_vR = 4 * np.pi / alpha3_inv_vR
gBL_sq_vR = 4 * np.pi / alphaBL_inv_vR

print(f"\n  g₃²(v_R) = {g3_sq_vR:.4f}")
print(f"  g_BL²(v_R) = {gBL_sq_vR:.4f}")

# =====================================================================
# PART 4: THE YUKAWA RATIO y_ν/y_u
# =====================================================================

print("\n" + "=" * 72)
print("PART 4: RUNNING OF y_ν/y_u FROM M_C TO v_R")
print("=" * 72)

# The RGE for the ratio R = y_ν/y_u:
# d ln R / dt = (1/16π²) × [gauge_ν - gauge_u + Yukawa_ν - Yukawa_u]
#
# Gauge contribution:
# For up-quark: -(8g₃² + 9/4 g₂L² + 9/4 g₂R² + 1/36 g_BL²)  [rough]
# For neutrino: -(           9/4 g₂L² + 9/4 g₂R² + 1/4  g_BL²)  [rough]
#
# Actually, let me use the exact PS normalization.
# In the LR model with B-L charges Q_BL(q) = 1/3, Q_BL(ℓ) = -1:
#
# Gauge contribution to y_u RGE:
#   -C₂(3) g₃² - C₂(2_L) g₂L² - C₂(2_R) g₂R² - Q²_BL g_BL²
#   = -8/3 g₃² - 3/4 g₂L² - 3/4 g₂R² - 1/9 g_BL²
#   (Wait, C₂(3) for fundamental of SU(3) = 4/3, not 8/3)
#
# Let me be very precise:
# C₂(fund of SU(N)) = (N²-1)/(2N)
# C₂(fund of SU(3)) = 4/3
# C₂(fund of SU(2)) = 3/4
#
# For up-quark (3, 2, 1, +1/3):
#   gauge_u = -[C₂(3) g₃² + C₂(2_L) g₂L² + 0 × g₂R² + (1/3)² g_BL²]
#           = -[4/3 × g₃² + 3/4 × g₂L² + (1/9) g_BL²]
# Wait, that's for left-handed u. For right-handed u (3, 1, 2, +1/3):
#   gauge_uR = -[4/3 × g₃² + 3/4 × g₂R² + (1/9) g_BL²]
#
# The YUKAWA coupling y_u involves both ψ_L and ψ_R. The anomalous dimension
# picks up contributions from both. For the standard RGE:
#   γ_Y = (contribution from ψ_L) + (contribution from ψ_R) + (contribution from Φ)
#
# In the LR model, the Yukawa y_u couples:
#   ψ_L(3, 2, 1, 1/3) × ψ_R(3, 1, 2, 1/3) × Φ(1, 2, 2, 0)
#
# Gauge anomalous dimension:
#   γ_gauge(y_u) = -[C₂(3)_L + C₂(2)_L + Q²_BL(q)] g₃²,g₂L²,g_BL²
#                  -[C₂(3)_R + C₂(2)_R + Q²_BL(q)] g₃²,g₂R²,g_BL²
#
# More cleanly: the full gauge contribution to d(ln y_u)/dt is:
#   = -(1/16π²) × [C₂ᴸ(ψ) + C₂ᴿ(ψ) + C₂(Φ)]
#   = -(1/16π²) × [(4/3 g₃² + 3/4 g₂L² + (1/9) g_BL²)    (from ψ_L)
#                  + (4/3 g₃² + 3/4 g₂R² + (1/9) g_BL²)    (from ψ_R)
#                  + (3/4 g₂L² + 3/4 g₂R² + 0)]            (from Φ)]

# For neutrino Yukawa (lepton sector):
# ψ_L(1, 2, 1, -1) × ψ_R(1, 1, 2, -1) × Φ(1, 2, 2, 0)
#   = -(1/16π²) × [(3/4 g₂L² + g_BL²)                      (from ψ_L, no SU(3))
#                  + (3/4 g₂R² + g_BL²)                      (from ψ_R, no SU(3))
#                  + (3/4 g₂L² + 3/4 g₂R² + 0)]             (from Φ)]

# The DIFFERENCE (ν minus u):
# Δ_gauge = gauge_ν - gauge_u
#   = -(1/16π²) × [(-8/3 g₃² + g_BL² - 1/9 g_BL²) + (-8/3 g₃² + g_BL² - 1/9 g_BL²)]
#   Wait, let me just subtract term by term:
#
# From ψ_L: (3/4 g₂L² + g_BL²) - (4/3 g₃² + 3/4 g₂L² + 1/9 g_BL²)
#          = -4/3 g₃² + 8/9 g_BL²
#
# From ψ_R: (3/4 g₂R² + g_BL²) - (4/3 g₃² + 3/4 g₂R² + 1/9 g_BL²)
#          = -4/3 g₃² + 8/9 g_BL²
#
# From Φ: same for both (cancels in the ratio)
#
# Total: Δ_gauge = -(1/16π²) × 2 × (-4/3 g₃² + 8/9 g_BL²)
#       = (1/16π²) × (8/3 g₃² - 16/9 g_BL²)

# d ln(y_ν/y_u)/dt = (1/16π²) × (8/3 g₃² - 16/9 g_BL²) + (Yukawa contributions)

# Since g₃² >> g_BL² at all relevant scales:
# d ln(y_ν/y_u)/dt > 0  (for running DOWN from M_C)
# → y_ν/y_u GROWS at low energy → WRONG DIRECTION

print("""
The gauge contribution to d ln(y_ν/y_u) / dt:

  d ln R/dt = (1/16π²) × (8/3 × g₃² - 16/9 × g_BL²) + (Yukawa terms)

The first term (8/3 × g₃²) is from SU(3) acting on quarks but not leptons.
The second term (-16/9 × g_BL²) is from the B-L charge difference.

Since g₃² >> g_BL² at all relevant scales:
  → d ln R/dt > 0 when running DOWN (increasing t means higher μ)
  → Wait, t = ln(μ), so running DOWN means t decreasing.
  → d ln R/dt > 0 means R increases with μ, decreases with lower μ...

Let me be explicit about sign conventions.
""")

# Let's just integrate numerically. Define t = ln(μ/GeV).
# Run from t_MC = ln(M_C) down to t_vR = ln(v_R).

# Use average gauge couplings for a simple estimate first
g3_sq_avg = 4 * np.pi * 2 / (alpha_PS_inv + alpha3_inv_vR)
gBL_sq_avg = 4 * np.pi * 2 / (alpha_PS_inv + alphaBL_inv_vR)

print(f"Average gauge couplings between M_C and v_R:")
print(f"  g₃²(avg) = {g3_sq_avg:.4f}")
print(f"  g_BL²(avg) = {gBL_sq_avg:.4f}")

# The coefficient of the RGE for ln(R):
# Using t running from high to low (t decreasing):
# We integrate from t_MC down to t_vR.
# d ln R / dt = (1/16π²) × (8/3 g₃² - 16/9 g_BL²)
# (ignoring Yukawa contributions for now — they're generation-dependent)

coeff_gauge = (8/3 * g3_sq_avg - 16/9 * gBL_sq_avg) / (16 * np.pi**2)
delta_t = t_vR - t_MC  # negative (running down)

delta_ln_R_gauge = coeff_gauge * delta_t

print(f"\nGauge-only estimate:")
print(f"  Coefficient = (8/3 × {g3_sq_avg:.4f} - 16/9 × {gBL_sq_avg:.4f}) / (16π²)")
print(f"             = {coeff_gauge:.6f}")
print(f"  Δt = ln(v_R/M_C) = {delta_t:.2f}")
print(f"  Δ ln R = {delta_ln_R_gauge:.4f}")
print(f"  R(v_R) / R(M_C) = exp(Δ ln R) = {np.exp(delta_ln_R_gauge):.4f}")

# R(M_C) = 1 (from b/a = 0)
R_vR_gauge = np.exp(delta_ln_R_gauge)
print(f"\n  y_ν/y_u at v_R = {R_vR_gauge:.4f}")
print(f"  m_D(ν) / m_D(u) at v_R = {R_vR_gauge:.4f}")

if R_vR_gauge > 1:
    print(f"\n  *** WRONG DIRECTION: neutrinos get HEAVIER relative to quarks ***")
    print(f"  The SU(3) gauge loops SUPPRESS quark Yukawas (enhance quark masses)")
    print(f"  relative to lepton Yukawas. This WORSENS the neutrino mass tension.")
elif R_vR_gauge < 1:
    print(f"\n  *** RIGHT DIRECTION: neutrinos get lighter relative to quarks ***")
    print(f"  Suppression factor: {1/R_vR_gauge:.2f}")

# =====================================================================
# PART 5: FULL NUMERICAL RGE (INCLUDING YUKAWA)
# =====================================================================

print("\n" + "=" * 72)
print("PART 5: FULL NUMERICAL RGE WITH YUKAWA CONTRIBUTIONS")
print("=" * 72)

print("""
Now include the Yukawa trace contributions. These are generation-dependent.

For the ratio R_i = y_ν_i / y_u_i of generation i:

  d ln R_i/dt = (1/16π²) × [gauge_diff + yukawa_diff_i]

The Yukawa difference for generation i:
  yukawa_diff_i = Tr_ν - Tr_u
  = (3 y_u_i² + y_d_i² + ...) terms that differ for quarks vs leptons

In practice, the dominant Yukawa effect comes from:
  - For 3rd gen: y_t² is large → significant modification
  - For 1st/2nd gen: Yukawas are small → gauge dominates
""")

# Simple numerical integration
# State: [ln(R_1), ln(R_2), ln(R_3), α₃⁻¹, α_BL⁻¹]
# where R_i = y_ν_i / y_u_i

# Yukawa couplings at M_C (from b/a = 0, so y_ν = y_u):
# Generation 1: y_u ≈ m_u/v ≈ 0.001/174 ≈ 6×10⁻⁶
# Generation 2: y_c ≈ 0.5/174 ≈ 3×10⁻³
# Generation 3: y_t ≈ 100/174 ≈ 0.57  (at M_C, reduced from pole)

y_u = [6e-6, 3e-3, 0.57]
y_d = [3e-6, 6e-4, 0.02]  # approximate
y_e = [3e-6, 6e-4, 0.01]  # approximate

print(f"Yukawa couplings at M_C:")
for i in range(3):
    print(f"  Gen {i+1}: y_u = {y_u[i]:.2e}, y_d = {y_d[i]:.2e}")

# For the Yukawa contribution to the ratio RGE:
# The key term is the anomalous dimension difference.
# In the LR model, the Yukawa anomalous dimension for y_u_i includes:
#   (3/2) y_u_i² + (3/2) y_d_i² + Tr(3 Y_u Y_u† + 3 Y_d Y_d† + Y_ν Y_ν† + Y_e Y_e†)
# The trace term is the same for quarks and leptons (it's summed over all).
# BUT the (3/2) y_i² terms differ because:
#   For y_u: (3/2)(y_u² + y_d²)
#   For y_ν: (3/2)(y_ν² + y_e²)
# Since y_ν = R × y_u, this gives a correction proportional to (R² - 1) y_u².

# The color factor also matters:
# For quarks, the trace over colors gives a factor of 3 in the Yukawa trace
# For leptons, no color factor
# This means the Yukawa trace contributes differently to y_u and y_ν.

# The net Yukawa contribution to d ln R_i/dt:
# For large y_t (3rd gen), the dominant term is:
#   ~ -(1/16π²) × 3 × y_t²  (quarks have 3 colors in the trace)
# which INCREASES y_u_3 faster than y_ν_3
# → R_3 = y_ν_3/y_u_3 DECREASES

# Wait, that would go the RIGHT way! Let me be more careful.

# The Yukawa anomalous dimension for y_u (quark Yukawa):
#   γ(y_u) includes: ... + (1/2) Tr(3 Y_u Y_u†) + ...
# The "3" is the COLOR FACTOR — quarks contribute 3× in the trace.
#
# For y_ν (lepton Yukawa):
#   γ(y_ν) includes: ... + (1/2) Tr(Y_ν Y_ν†) + ...
# The trace over the SU(4) multiplet gives:
#   quark contribution: 3 × y_u² (3 colors)
#   lepton contribution: y_ν²
#
# So the Yukawa trace contributes:
#   To y_u: (1/2)(3 × Σ y_u² + Σ y_ν²)  (sum over generations)
#   To y_ν: (1/2)(3 × Σ y_u² + Σ y_ν²)  (SAME — it's a trace)
# These are the SAME for y_u and y_ν! So the trace cancels in the ratio.

# The NON-trace Yukawa term is the self-energy:
#   For y_u_i: +(3/2)(y_u_i† y_u_i) + (1/2)(y_d_i† y_d_i) ... (from wave function)
#   For y_ν_i: +(3/2)(y_ν_i† y_ν_i) + (1/2)(y_e_i† y_e_i) ...
# These are DIFFERENT, and the difference is:
#   (3/2)(y_ν² - y_u²) + (1/2)(y_e² - y_d²)
# With R = y_ν/y_u and initially R = 1, this starts at zero.
# As R evolves (from gauge effects), this becomes a feedback term.

# Actually, there's another important term: the SU(3) vertex correction.
# The quark Yukawa gets a vertex correction from gluon exchange:
#   δ(y_u)/y_u ~ +2 C₂(3) g₃²/(16π²) = +8/3 g₃²/(16π²)
# per loop. This correction is ABSENT for leptons.
# This is already captured in our gauge term above.

# So the dominant effect is purely from gauge running.
# The Yukawa self-energy feedback is secondary (starts at zero for R=1).

# Let me do the full numerical integration anyway.

def rge_system(t, state):
    """
    RGE system for y_ν/y_u ratios and gauge couplings.
    state = [lnR1, lnR2, lnR3, alpha3_inv, alphaBL_inv]
    t = ln(μ/GeV), running downward from t_MC to t_vR
    """
    lnR = state[:3]
    a3_inv = state[3]
    aBL_inv = state[4]

    g3_sq = 4 * np.pi / a3_inv if a3_inv > 0 else 100
    gBL_sq = 4 * np.pi / aBL_inv if aBL_inv > 0 else 100

    # Gauge contribution to d(lnR)/dt
    # Note: we're running t downward, so dt < 0 means lower μ
    # The RGE with our sign convention: d(lnR)/dt = coefficient
    # where running from high to low t, lnR changes by coeff × Δt

    # From the derivation above:
    # d ln R/dt = (1/16π²) × (8/3 g₃² - 16/9 g_BL²)
    gauge_coeff = (8/3 * g3_sq - 16/9 * gBL_sq) / (16 * np.pi**2)

    # Yukawa feedback (secondary):
    # The self-energy difference is (3/2)(y_ν² - y_u²)/y_u²
    # = (3/2)(R² - 1)y_u²/(16π²)
    # For R ~ 1, this is ~ (3/2)(2δR)y_u²/(16π²) ≈ 0 initially
    # Include it for completeness:
    yukawa_feedback = np.zeros(3)
    for i in range(3):
        Ri = np.exp(lnR[i])
        # Self-energy correction
        yu_sq = y_u[i]**2 * Ri  # rough: y_ν = R × y_u
        yukawa_feedback[i] = (3/2) * (Ri**2 - 1) * y_u[i]**2 / (16 * np.pi**2)

    dlnR_dt = np.array([gauge_coeff + yukawa_feedback[i] for i in range(3)])

    # Gauge beta functions
    da3_inv_dt = -b3_LR / (2 * np.pi)
    daBL_inv_dt = -bBL_LR / (2 * np.pi)

    return np.concatenate([dlnR_dt, [da3_inv_dt, daBL_inv_dt]])

# Initial conditions at M_C
state0 = np.array([0.0, 0.0, 0.0, alpha_PS_inv, alpha_PS_inv])

# Integrate from t_MC down to t_vR
sol = solve_ivp(rge_system, [t_MC, t_vR], state0, rtol=1e-10, atol=1e-12,
                max_step=0.5)

if sol.success:
    lnR_final = sol.y[:3, -1]
    R_final = np.exp(lnR_final)
    a3_final = sol.y[3, -1]
    aBL_final = sol.y[4, -1]

    print(f"\nResults of full RGE integration (M_C → v_R):")
    print(f"  α₃⁻¹(v_R) = {a3_final:.2f}")
    print(f"  α_BL⁻¹(v_R) = {aBL_final:.2f}")

    for i in range(3):
        print(f"\n  Generation {i+1}:")
        print(f"    y_ν/y_u ratio at v_R: R = {R_final[i]:.6f}")
        print(f"    ln(R) = {lnR_final[i]:.6f}")

        # Compute neutrino masses
        m_D_u = y_u[i] * 174  # Dirac mass (GeV)
        m_D_nu = R_final[i] * m_D_u  # Modified by running
        v_R_val = 1.1e9
        f_val = 1.0
        m_nu = m_D_nu**2 / (f_val * v_R_val)  # Type-I seesaw
        m_nu_eV = m_nu * 1e9

        print(f"    m_D(u) = {m_D_u:.4e} GeV")
        print(f"    m_D(ν) = {m_D_nu:.4e} GeV  (= R × m_D(u))")
        print(f"    m_ν = m_D(ν)² / v_R = {m_nu:.4e} GeV = {m_nu_eV:.4e} eV")

    # Summary table
    print(f"\n" + "=" * 72)
    print("SUMMARY: NEUTRINO MASSES WITH RADIATIVE b/a SPLITTING")
    print("=" * 72)

    print(f"\n{'Gen':>4} {'R=y_ν/y_u':>10} {'m_D(u)':>12} {'m_D(ν)':>12} {'m_ν (eV)':>12} {'Observed':>12} {'Tension':>10}")
    print("-" * 80)
    for i in range(3):
        m_D_u = y_u[i] * 174
        m_D_nu = R_final[i] * m_D_u
        m_nu = m_D_nu**2 / (1.0 * 1.1e9)
        m_nu_eV = m_nu * 1e9
        obs = [0.001, 0.009, 0.05][i]
        tension = m_nu_eV / obs
        print(f"  {i+1:>2}  {R_final[i]:>10.4f}  {m_D_u:>10.2e} GeV  {m_D_nu:>10.2e} GeV  {m_nu_eV:>10.2e}  {obs:>10.4f}  {tension:>8.1f}×")

    print(f"""
INTERPRETATION:

The gauge RGE running from M_C to v_R shifts the y_ν/y_u ratio by:
  R = {R_final[2]:.4f}  (for 3rd generation)

This is a {abs(R_final[2]-1)*100:.1f}% effect — {'INCREASING' if R_final[2] > 1 else 'DECREASING'} m_D(ν) relative to m_D(u).
""")

    if R_final[2] > 1:
        print("""The radiative b/a splitting goes the WRONG DIRECTION for neutrino masses.
The SU(3) gauge correction makes quark Yukawas RUN FASTER (quarks get
relatively heavier), which means y_ν/y_u INCREASES at low energy.

This is the same effect that gives m_b ≠ m_τ in SU(5) GUTs:
  m_b/m_τ = 1 at M_GUT → m_b/m_τ ≈ 3 at M_Z (SU(3) enhancement)

In our case, it means:
  m_D(ν₃)/m_D(t) = 1 at M_C → m_D(ν₃)/m_D(t) > 1 at v_R

The neutrino mass tension gets WORSE, not better, from RGE running.

CONCLUSION: Path 2 (radiative b/a splitting) does NOT help.
The required suppression factor of ~400 for the 3rd generation
cannot come from gauge RGE — it goes in the wrong direction.

This leaves:
  (a) Inverse seesaw with μ_S as a parameter
  (b) Some mechanism that makes f >> 1 for the Δ_R Majorana coupling
  (c) Modified seesaw structure (type-II, type-III, etc.)
  (d) Accept as open problem — standard PS models do the same
""")
    else:
        suppression = 1/R_final[2]
        needed = 400  # for 3rd gen
        print(f"Suppression factor: {suppression:.1f}")
        print(f"Needed for 3rd gen: {needed}")
        if suppression > needed:
            print("*** SUFFICIENT — tension resolved by RGE running! ***")
        else:
            print(f"Insufficient: only {suppression:.1f}× of the needed {needed}×")

else:
    print(f"Integration failed: {sol.message}")

# =====================================================================
# PART 6: THE m_b/m_τ ANALOGY
# =====================================================================

print("\n" + "=" * 72)
print("PART 6: THE m_b/m_τ ANALOGY (GEORGI-JARLSKOG)")
print("=" * 72)

print("""
In SU(5) GUTs, the tree-level relation m_b = m_τ at M_GUT gets modified
by RGE running to m_b/m_τ ≈ 3 at M_Z. This is because:

  d ln(y_b/y_τ)/dt ~ +(1/16π²) × 8/3 × g₃²

(quarks get enhanced by gluon loops, leptons don't)

The SAME effect applies to our m_D(ν)/m_D(u) ratio, but in the
OPPOSITE direction from what we need:

  SU(5):  m_b = m_τ at GUT → m_b/m_τ ~ 3 at M_Z  (quarks heavier: GOOD)
  PS:     m_D(ν) = m_u at M_C → m_D(ν)/m_u > 1 at v_R  (neutrinos heavier: BAD)

The Georgi-Jarlskog mechanism in SU(5) USES the Clebsch-Gordan coefficients
of the GUT group to get m_b ≠ m_τ at tree level. The analogous PS mechanism
would use the (15,2,2) Yukawa to get m_D(ν) ≠ m_u at tree level.

But in the metric bundle, b/a = 0 at tree level → no (15,2,2).
The radiative correction generates b/a ~ O(α_s/4π) but this goes the
WRONG WAY (makes neutrinos relatively heavier).

This is the fundamental problem: SU(3) gauge loops help with m_b/m_τ
but HURT the neutrino mass prediction.
""")

# Compute the GJ-like ratio
if sol.success:
    # The m_b/m_τ analogy: how much does the ratio shift?
    ln_ratio_shift = np.log(R_final[2])
    print(f"Shift in ln(y_ν₃/y_t): {ln_ratio_shift:.4f}")
    print(f"Corresponding ratio: {R_final[2]:.4f}")
    print(f"This is a {(R_final[2]-1)*100:.1f}% effect over {np.log10(M_C/v_R):.1f} decades of running")
    print(f"\nFor comparison, the SU(5) m_b/m_τ effect is:")
    print(f"  m_b/m_τ shifts from 1 to ~3 over ~14 decades")
    print(f"  ln(m_b/m_τ) ~ 1.1 over Δt ~ 14/2π ~ 2.2")
    print(f"  Rate: ~0.5 per unit t")
    print(f"\nOur effect:")
    print(f"  y_ν/y_u shifts by ln(R) = {ln_ratio_shift:.4f} over Δt = {(t_MC-t_vR)/(2*np.pi):.2f}")
    print(f"  Rate: {ln_ratio_shift/((t_MC-t_vR)/(2*np.pi)):.4f} per unit t")
