"""
Tunneling and Instanton Methods
================================

Core capability: compute tunneling amplitudes exp(-S_eff) on
non-compact symmetric spaces.

Key quantities:
  - Instanton action S_inst on G/H
  - Effective degrees of freedom N_eff from geometry
  - Tunneling amplitude A = exp(-S_inst)
  - Non-perturbative scale Lambda_NP = Lambda_UV * exp(-S_inst)

This is the central module that transfers to condensed matter,
catalysis, LENR, and topological QC applications.

Generalized from the instanton estimate in coleman_weinberg_su2R.py.
"""

import numpy as np
import math
from dataclasses import dataclass, field
from typing import Optional, Tuple, Callable, List, Dict, Any
from scipy.integrate import solve_ivp, quad
from scipy.optimize import brentq, minimize_scalar, minimize


_trapz = getattr(np, 'trapezoid', getattr(np, 'trapz', None))


@dataclass
class InstantonConfig:
    """Configuration for an instanton computation on G/H."""

    coupling: float          # Gauge coupling g at the relevant scale
    Lambda_UV: float         # UV scale (e.g., M_C)
    N_eff: Optional[float] = None  # Effective DOF (computed or specified)
    topological_charge: int = 1     # Winding number


class InstantonAction:
    """Compute instanton actions on symmetric spaces."""

    def __init__(self, dim_fibre: int, dim_isotropy: int):
        """
        Args:
            dim_fibre: Dimension of the tangent space p
            dim_isotropy: Dimension of the isotropy algebra h
        """
        self.dim_p = dim_fibre
        self.dim_h = dim_isotropy

    def standard_action(self, g: float, n: int = 1) -> float:
        """Standard instanton action S = 8 pi^2 n / g^2.

        This is the BPST result for SU(2) instantons. For other groups,
        the action is S = 8 pi^2 n / (N_eff * g^2) where N_eff accounts
        for the effective number of participating degrees of freedom.
        """
        return 8 * math.pi**2 * n / g**2

    def effective_action(self, g: float, N_eff: float, n: int = 1) -> float:
        """Effective instanton action with N_eff correction.

        S_eff = 8 pi^2 n / (N_eff * g^2)

        N_eff > 1 means the instanton spreads over multiple DOF,
        reducing the action per DOF and enhancing tunneling.
        """
        return 8 * math.pi**2 * n / (N_eff * g**2)

    def tunneling_amplitude(self, S: float) -> float:
        """Tunneling amplitude A = exp(-S)."""
        return math.exp(-S)

    def nonperturbative_scale(self, Lambda_UV: float, g: float,
                               N_eff: float, n: int = 1) -> float:
        """Non-perturbative scale Lambda_NP = Lambda_UV * exp(-S_eff).

        This is the scale generated by dimensional transmutation
        via instantons.
        """
        S = self.effective_action(g, N_eff, n)
        return Lambda_UV * math.exp(-S)

    def N_eff_for_target_scale(self, Lambda_UV: float, Lambda_target: float,
                                g: float) -> float:
        """Compute N_eff needed to generate a specific scale.

        Given Lambda_target = Lambda_UV * exp(-8pi^2 / (N_eff * g^2)),
        solve for N_eff.
        """
        S_needed = math.log(Lambda_UV / Lambda_target)
        return 8 * math.pi**2 / (S_needed * g**2)

    def scan_N_eff(self, Lambda_UV: float, g: float,
                    N_eff_range: Tuple[float, float] = (1, 30)) -> list:
        """Scan instanton scale as a function of N_eff.

        Returns list of (N_eff, Lambda_NP, log10_Lambda_NP).
        """
        results = []
        for N in np.linspace(N_eff_range[0], N_eff_range[1], 100):
            Lambda_NP = self.nonperturbative_scale(Lambda_UV, g, N)
            log_Lambda = math.log10(max(Lambda_NP, 1e-300))
            results.append((N, Lambda_NP, log_Lambda))
        return results


class N_eff_Calculator:
    """Compute N_eff from the geometry of the symmetric space.

    N_eff is the effective number of degrees of freedom participating
    in the instanton. It depends on:
    1. The dimension of the fibre (dim_p)
    2. The topology (pi_3 of the isotropy group)
    3. The metric structure (eigenvalues of the DeWitt metric)
    """

    def __init__(self, dim_p: int, dim_h: int):
        self.dim_p = dim_p
        self.dim_h = dim_h

    def from_dimension_counting(self) -> float:
        """Simplest estimate: N_eff = dim_p.

        This counts all directions in the tangent space as participating.
        Gives an upper bound.
        """
        return float(self.dim_p)

    def from_metric_eigenvalues(self, eigenvalues: np.ndarray) -> float:
        """Compute N_eff from the metric eigenvalue spectrum.

        N_eff = (sum |lambda_i|)^2 / (sum lambda_i^2)

        This is the "participation ratio" — it measures how many
        eigenvalues contribute significantly. For equal eigenvalues,
        N_eff = dim_p. For one dominant eigenvalue, N_eff = 1.
        """
        abs_eigs = np.abs(eigenvalues[np.abs(eigenvalues) > 1e-15])
        if len(abs_eigs) == 0:
            return 0.0
        return float(np.sum(abs_eigs)**2 / np.sum(abs_eigs**2))

    def from_positive_sector(self, positive_eigenvalues: np.ndarray) -> float:
        """N_eff from V+ sector only (gauge DOF)."""
        return self.from_metric_eigenvalues(positive_eigenvalues)

    def from_instanton_profile(self, action_profile: Callable,
                                R_range: Tuple[float, float] = (0.01, 100)) -> float:
        """Compute N_eff from the radial profile of the instanton solution.

        N_eff = integral of the action density over the instanton profile.
        """
        S_total, _ = quad(action_profile, R_range[0], R_range[1])
        S_unit = 8 * math.pi**2  # Standard BPST action
        return S_unit / max(S_total, 1e-30)


class BarrierTunneling:
    """Compute tunneling rates through potential barriers.

    This is the general framework applicable to:
    - Coulomb barrier (LENR)
    - Phase transitions (condensed matter)
    - Catalytic reactions (transition states)
    """

    def __init__(self, potential: Callable, mass: float = 1.0):
        """
        Args:
            potential: V(x) — the potential barrier
            mass: Effective mass (or reduced mass)
        """
        self.V = potential
        self.mass = mass

    def wkb_action(self, x_a: float, x_b: float, E: float,
                    n_points: int = 1000) -> float:
        """WKB tunneling action S = integral sqrt(2m(V-E)) dx.

        This is the semiclassical approximation valid when S >> hbar.
        """
        x = np.linspace(x_a, x_b, n_points)
        integrand = np.zeros(n_points)
        for i, xi in enumerate(x):
            V_minus_E = self.V(xi) - E
            if V_minus_E > 0:
                integrand[i] = math.sqrt(2 * self.mass * V_minus_E)
        # np.trapezoid (numpy >= 2.0) or np.trapz (numpy < 2.0)
        _trapz = getattr(np, 'trapezoid', getattr(np, 'trapz', None))
        return float(_trapz(integrand, x))

    def wkb_rate(self, x_a: float, x_b: float, E: float) -> float:
        """WKB tunneling rate Gamma ~ exp(-2S/hbar).

        Returns the exponential suppression factor (no prefactor).
        """
        S = self.wkb_action(x_a, x_b, E)
        return math.exp(-2 * S)

    def bounce_solution(self, x_init: float, E: float,
                         x_range: Tuple[float, float] = (0, 100),
                         n_points: int = 1000) -> Tuple[np.ndarray, np.ndarray]:
        """Find the bounce (instanton) solution in the inverted potential.

        The bounce satisfies: x'' = -dV/dx with V -> -V (Euclidean time).
        """
        def dV_dx(x):
            eps = abs(x) * 1e-8 + 1e-12
            return (self.V(x + eps) - self.V(x - eps)) / (2 * eps)

        def equations(t, y):
            x, v = y
            return [v, dV_dx(x)]  # Note: +dV/dx because inverted potential

        sol = solve_ivp(
            equations, x_range, [x_init, 0.0],
            method='RK45', max_step=0.1,
            t_eval=np.linspace(x_range[0], x_range[1], n_points)
        )
        return sol.t, sol.y[0]

    def enhanced_tunneling(self, S_bare: float, N_eff: float) -> float:
        """Tunneling rate with N_eff collective enhancement.

        The idea: if N_eff modes participate collectively,
        the effective action is reduced: S_eff = S_bare / N_eff.
        """
        return math.exp(-S_bare / N_eff)


# =====================================================================
# ARM 2: Condensed matter tunneling classes
# =====================================================================

@dataclass
class TunnelingResult:
    """Result of a tunneling computation."""
    action: float
    rate_exponent: float
    rate: float
    method: str
    prefactor: float = 1.0
    metadata: Optional[dict] = None

    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}


class DoubleWell:
    """Symmetric double-well potential V(x) = λ(x² - a²)².

    Exact instanton: x(τ) = a tanh(ωτ/2)
    Exact action: S_E = (4/3) a³ √(2mλ)
    """

    def __init__(self, a: float = 1.0, lam: float = 1.0, mass: float = 1.0):
        self.a = a
        self.lam = lam
        self.mass = mass

    @property
    def omega(self) -> float:
        """ω = 2a√(2λ/m)."""
        return 2 * self.a * math.sqrt(2 * self.lam / self.mass)

    @property
    def barrier_height(self) -> float:
        """V(0) = λa⁴."""
        return self.lam * self.a ** 4

    def V(self, x: float) -> float:
        return self.lam * (x ** 2 - self.a ** 2) ** 2

    def dVdx(self, x: float) -> float:
        return 4 * self.lam * x * (x ** 2 - self.a ** 2)

    def instanton(self, tau: np.ndarray) -> np.ndarray:
        """x(τ) = a tanh(ωτ/2)."""
        return self.a * np.tanh(self.omega * tau / 2)

    def exact_action(self) -> float:
        """S_E = (4/3) a³ √(2mλ)."""
        return (4.0 / 3.0) * self.a ** 3 * math.sqrt(2 * self.mass * self.lam)

    def exact_splitting(self) -> float:
        """ΔE ~ ω √(S/(2π)) exp(-S)."""
        S = self.exact_action()
        if S > 700:
            return 0.0
        return self.omega * math.sqrt(S / (2 * math.pi)) * math.exp(-S)

    def numerical_check(self, n_points: int = 2000) -> dict:
        """Compare exact action to numerical WKB integral."""
        x = np.linspace(-self.a, self.a, n_points)
        integrand = np.array([math.sqrt(2 * self.mass * self.V(xi))
                              if self.V(xi) > 0 else 0.0 for xi in x])
        numerical = float(_trapz(integrand, x))
        exact = self.exact_action()
        return {
            'numerical_action': numerical,
            'exact_action': exact,
            'ratio': numerical / exact if exact > 0 else float('inf'),
        }

    def tunneling_result(self) -> TunnelingResult:
        S = self.exact_action()
        return TunnelingResult(
            action=S, rate_exponent=-S,
            rate=math.exp(-S) if S < 700 else 0.0,
            method='exact_double_well',
            metadata={'a': self.a, 'lambda': self.lam, 'mass': self.mass,
                      'omega': self.omega, 'barrier': self.barrier_height,
                      'splitting': self.exact_splitting()},
        )


class Tunneling1D:
    """General 1D tunneling through an arbitrary potential."""

    def __init__(self, V: Callable, dVdx: Callable, mass: float = 1.0):
        self.V = V
        self.dVdx = dVdx
        self.mass = mass

    def wkb_action(self, x_a: float, x_b: float, E: float = 0.0,
                    n_points: int = 2000) -> float:
        """S = ∫ √(2m(V-E)) dx."""
        x = np.linspace(x_a, x_b, n_points)
        integrand = np.zeros(n_points)
        for i, xi in enumerate(x):
            V_minus_E = self.V(xi) - E
            if V_minus_E > 0:
                integrand[i] = math.sqrt(2 * self.mass * V_minus_E)
        return float(_trapz(integrand, x))

    def find_minima(self, x_range: Tuple[float, float] = (-5, 5),
                     n_scan: int = 1000) -> list:
        x_scan = np.linspace(x_range[0], x_range[1], n_scan)
        V_scan = np.array([self.V(xi) for xi in x_scan])
        minima = []
        for i in range(1, n_scan - 1):
            if V_scan[i] < V_scan[i - 1] and V_scan[i] < V_scan[i + 1]:
                result = minimize_scalar(self.V, bounds=(x_scan[i - 1], x_scan[i + 1]),
                                          method='bounded')
                minima.append((result.x, result.fun))
        return minima


class JosephsonJunction:
    """Macroscopic quantum tunneling in a Josephson junction.

    Washboard potential near I → I_c, cubic approximation.
    """

    def __init__(self, E_J: float = 1.0, bias_ratio: float = 0.9,
                 capacitance: float = 1.0):
        self.E_J = E_J
        self.s = bias_ratio
        self.C = capacitance

    @property
    def barrier_height(self) -> float:
        """ΔU = (4√2/3) E_J (1-s)^{3/2}."""
        return (4 * math.sqrt(2) / 3) * self.E_J * (1 - self.s) ** 1.5

    @property
    def plasma_frequency(self) -> float:
        """ω_p = √(2E_J/C) × (1-s²)^{1/4}."""
        return math.sqrt(2 * self.E_J / self.C) * (1 - self.s ** 2) ** 0.25

    def tunneling_rate(self) -> TunnelingResult:
        """Caldeira-Leggett MQT rate."""
        omega_p = self.plasma_frequency
        delta_U = self.barrier_height
        if omega_p <= 0:
            return TunnelingResult(action=float('inf'), rate_exponent=-float('inf'),
                                    rate=0.0, method='josephson_cubic')
        S = 36 * delta_U / (5 * omega_p)
        A = 12 * math.sqrt(6 * math.pi * S)
        return TunnelingResult(
            action=S, rate_exponent=-S,
            rate=A * omega_p * math.exp(-S) if S < 700 else 0.0,
            method='josephson_cubic', prefactor=A * omega_p,
            metadata={'E_J': self.E_J, 'bias_ratio': self.s,
                      'barrier_height': delta_U, 'plasma_frequency': omega_p},
        )

    def crossover_temperature(self) -> float:
        """T* = ω_p/(2π)."""
        return self.plasma_frequency / (2 * math.pi)


class TunnelingND:
    """Multi-dimensional tunneling with Hessian analysis."""

    def __init__(self, V: Callable, n_dim: int):
        self.V = V
        self.n_dim = n_dim

    def straight_line_action(self, x_a: np.ndarray, x_b: np.ndarray,
                              mass: float = 1.0, n_points: int = 2000) -> float:
        """WKB action along straight line from x_a to x_b."""
        s = np.linspace(0, 1, n_points)
        dx = x_b - x_a
        length = np.linalg.norm(dx)
        integrand = np.zeros(n_points)
        for i, si in enumerate(s):
            x = x_a + si * dx
            Vi = self.V(x)
            if Vi > 0:
                integrand[i] = math.sqrt(2 * mass * Vi)
        return float(length * _trapz(integrand, s))

    def n_eff_from_hessian(self, x_saddle: np.ndarray, eps: float = 1e-5) -> dict:
        """N_eff from Hessian eigenvalues at saddle point."""
        n = self.n_dim
        H = np.zeros((n, n))
        for i in range(n):
            for j in range(i, n):
                ei = np.zeros(n); ej = np.zeros(n)
                ei[i] = eps; ej[j] = eps
                Vpp = self.V(x_saddle + ei + ej)
                Vpm = self.V(x_saddle + ei - ej)
                Vmp = self.V(x_saddle - ei + ej)
                Vmm = self.V(x_saddle - ei - ej)
                H[i, j] = (Vpp - Vpm - Vmp + Vmm) / (4 * eps ** 2)
                H[j, i] = H[i, j]
        eigs = np.linalg.eigvalsh(H)
        n_neg = int(np.sum(eigs < -1e-10))
        abs_eigs = np.abs(eigs[np.abs(eigs) > 1e-15])
        N_eff = float(np.sum(abs_eigs) ** 2 / np.sum(abs_eigs ** 2)) if len(abs_eigs) > 0 else 0.0
        return {'eigenvalues': eigs, 'n_negative_modes': n_neg,
                'is_transition_state': n_neg == 1, 'N_eff': N_eff, 'hessian': H}


class SymmetricSpaceInstanton:
    """Instanton on G/H. Reproduces GL+(4)/SO(3,1): S = 8π²/g² ≈ 290."""

    def __init__(self, g_coupling: float, M_UV: float, pi3: str = 'Z'):
        self.g = g_coupling
        self.M_UV = M_UV
        self.pi3 = pi3

    @property
    def bpst_action(self) -> float:
        return 8 * math.pi ** 2 / self.g ** 2

    def hierarchy_ratio(self, N_eff: float) -> float:
        S = self.bpst_action
        return math.exp(-S / N_eff) if S / N_eff < 700 else 0.0

    def n_eff_for_target(self, target_ratio: float) -> float:
        return -self.bpst_action / math.log(target_ratio)

    def nonperturbative_scale(self, N_eff: float) -> float:
        return self.M_UV * self.hierarchy_ratio(N_eff)


def coulomb_barrier(Z1: int, Z2: int, screening_length: float = np.inf) -> Callable:
    """Coulomb potential between nuclei with optional screening.

    V(r) = Z1 * Z2 * e^2 / (4 pi epsilon_0 r) * exp(-r / lambda_s)

    In natural units (MeV, fm):
    V(r) = Z1 * Z2 * alpha_em * hbar_c / r * exp(-r/lambda_s)
    """
    alpha_em = 1.0 / 137.036
    hbar_c = 197.3  # MeV·fm

    def V(r):
        if r < 1e-5:
            return 1e10  # Regularize at origin
        screening = math.exp(-r / screening_length) if np.isfinite(screening_length) else 1.0
        return Z1 * Z2 * alpha_em * hbar_c / r * screening

    return V
